// 📦 Danh sách skin có thể bán trong Shop
// skins.js
export const SKINS = [
  {
    id: 'classic-x',
    name: 'X Cổ điển',
    icon: 'X',
    price: 0,
    description: 'Biểu tượng X cổ điển màu đỏ.',
  },
  {
    id: 'classic-o',
    name: 'O Cổ điển',
    icon: 'O',
    price: 0,
    description: 'Biểu tượng O cổ điển màu xanh.',
  },
  {
    id: 'default',
    name: 'X hiện đại',
    icon: '❌',
    price: 0,
    description: 'Biểu tượng X hiện đại.',
  },
  {
    id: 'ai-default',
    icon: '⭕',
    name: 'O hiện đại',
    price: 0,
    description: 'Biểu tượng O hiện đại.',
  },
  {
    id: 'tiger',
    name: 'Hổ Chiến',
    icon: '🐯',
    price: 50,
    description: 'Gầm vang bàn cờ!',
  },
  {
    id: 'robot',
    name: 'Robot AI',
    icon: '🤖',
    price: 75,
    description: 'Thông minh nhân tạo vượt trội.',
  },
  {
    id: 'ninja',
    name: 'Ninja',
    icon: '🥷',
    price: 100,
    description: 'Ẩn thân, ra đòn bất ngờ!',
  },
  {
    id: 'dragon',
    name: 'Rồng Lửa',
    icon: '🐉',
    price: 120,
    description: 'Khạc lửa mỗi nước đi.',
  },
  {
    id: 'ghost',
    name: 'Hồn Ma',
    icon: '👻',
    price: 90,
    description: 'Ám ảnh mọi đường cờ.',
  },
  {
    id: 'flame-dragon',
    name: 'Lửa',
    icon: '🔥',
    price: 110,
    description: 'Rực cháy và huyền bí.',
  },
  {
    id: 'ice-queen',
    name: 'Băng',
    icon: '❄️',
    price: 95,
    description: 'Lạnh lùng và kiêu sa.',
  },
  {
    id: 'cyber-nova',
    name: 'star',
    icon: '✨',
    price: 130,
    description: 'Trí tuệ nhân tạo tinh tú.',
  },
  {
    id: 'ghost-cat',
    name: 'MèoCute',
    icon: '🐱',
    price: 80,
    description: 'Im lặng nhưng nguy hiểm.',
  },
  {
    id: 'storm-sword',
    name: 'Kiếm',
    icon: '⚔️',
    price: 105,
    description: 'Chém rạch cả bàn cờ!',
  },
  {
    id: 'phoenix',
    name: 'Phượng Hoàng',
    icon: '🦜',
    price: 100,
    description: 'Hồi sinh từ tro tàn, bay cao bất tận.',
  },
  {
    id: 'ninja-star',
    name: 'Phi Tiêu Ninja',
    icon: '🌀',
    price: 70,
    description: 'Đòn đánh nhanh gọn, khó đoán.',
  },
  {
    id: 'space-core',
    name: 'Hạt Nhân Vũ Trụ',
    icon: '🪐',
    price: 120,
    description: 'Sức mạnh xoáy tâm không gian.',
  },
  {
    id: 'slime',
    name: 'Slime Dẻo',
    icon: '🟢',
    price: 60,
    description: 'Lầy lội và khó chịu bất ngờ.',
  },
  {
    id: 'vampire',
    name: 'Ma Cà Rồng',
    icon: '🧛',
    price: 90,
    description: 'Ẩn nấp trong bóng tối, hút máu chiến lược.',
  },
  {
    id: 'samurai-blade',
    name: 'Lưỡi Gươm Samurai',
    icon: '🗡️',
    price: 95,
    description: 'Tinh thần võ sĩ đạo sắc bén.',
  },
  {
    id: 'lunar-rabbit',
    name: 'Thỏ Ngọc',
    icon: '🐇',
    price: 85,
    description: 'Nhanh nhẹn và linh hoạt như trăng rằm.',
  },
  {
    id: 'alien-core',
    name: 'Nhân Tố Ngoài Hành Tinh',
    icon: '👽',
    price: 110,
    description: 'Thông minh... và hơi đáng sợ.',
  },
  {
    id: 'pirate-coin',
    name: 'Kho Báu Cướp Biển',
    icon: '💰',
    price: 90,
    description: 'Tỏa sáng như vàng thật.',
  },
  {
    id: 'nuclear-power',
    name: 'Lò Phản Ứng',
    icon: '☢️',
    price: 100,
    description: 'Nổ tung chiến lược đối thủ.',
  },
  {
    id: 'leaf-spirit',
    name: 'Tinh Linh Lá',
    icon: '🍃',
    price: 70,
    description: 'Nhẹ nhàng, không ai lường được.',
  },
  {
    id: 'star-legend',
    name: 'Ngôi Sao Huyền Thoại',
    icon: '⭐',
    price: 120,
    description: 'Toả sáng như người chiến thắng vĩ đại.',
  },
  {
    id: 'volcano',
    name: 'Núi Lửa Phun Trào',
    icon: '🌋',
    price: 95,
    description: 'Nóng bỏng và bùng nổ bất ngờ.',
  },
  {
    id: 'moonlight',
    name: 'Ánh Trăng',
    icon: '🌕',
    price: 80,
    description: 'Lặng lẽ nhưng chiếu sáng toàn bàn cờ.',
  },
  {
    id: 'robot-core',
    name: 'Trung Tâm Robot',
    icon: '🛸',
    price: 105,
    description: 'Điều khiển mọi nước đi bằng công nghệ.',
  },
  {
    id: 'devil-mask',
    name: 'Mặt Nạ Ác Quỷ',
    icon: '😈',
    price: 100,
    description: 'Đầy mưu mô và thách thức.',
  },
];
