// 📦 Danh sách skin có thể bán trong Shop
// skins.js
export const SKINS = [
  {
    id: 'classic-x',
    name: 'Cổ điển',
    icon: 'X',
    price: 0,
    description: 'Biểu tượng X cổ điển màu đỏ.',
  },
  {
    id: 'classic-o',
    name: 'Cổ điển',
    icon: 'O',
    price: 0,
    description: 'Biểu tượng O cổ điển màu xanh.',
  },
  {
    id: 'default',
    name: 'Cơ bản',
    icon: '❌',
    price: 0,
    description: 'Skin mặc định miễn phí.',
  },
  {
    id: 'ai-default',
    icon: '⭕',
    name: 'Cơ bản',
    price: 0,
    description: 'Skin mặc định miễn phí.',
  },
  {
    id: 'tiger',
    name: 'Hổ Chiến',
    icon: '🐯',
    price: 50,
    description: 'Gầm vang bàn cờ!',
  },
  {
    id: 'robot',
    name: 'Robot AI',
    icon: '🤖',
    price: 75,
    description: 'Thông minh nhân tạo vượt trội.',
  },
  {
    id: 'ninja',
    name: 'Ninja',
    icon: '🥷',
    price: 100,
    description: 'Ẩn thân, ra đòn bất ngờ!',
  },
  {
    id: 'dragon',
    name: 'Rồng Lửa',
    icon: '🐉',
    price: 120,
    description: 'Khạc lửa mỗi nước đi.',
  },
  {
    id: 'ghost',
    name: 'Hồn Ma',
    icon: '👻',
    price: 90,
    description: 'Ám ảnh mọi đường cờ.',
  },
  {
    id: 'flame-dragon',
    name: 'Lửa',
    icon: '🔥',
    price: 110,
    description: 'Rực cháy và huyền bí.',
  },
  {
    id: 'ice-queen',
    name: 'Băng',
    icon: '❄️',
    price: 95,
    description: 'Lạnh lùng và kiêu sa.',
  },
  {
    id: 'cyber-nova',
    name: 'star',
    icon: '✨',
    price: 130,
    description: 'Trí tuệ nhân tạo tinh tú.',
  },
  {
    id: 'ghost-cat',
    name: 'MèoCute',
    icon: '🐱',
    price: 80,
    description: 'Im lặng nhưng nguy hiểm.',
  },
  {
    id: 'storm-sword',
    name: 'Kiếm',
    icon: '⚔️',
    price: 105,
    description: 'Chém rạch cả bàn cờ!',
  },
  {
    id: 'phoenix',
    name: 'Phượng Hoàng',
    icon: '🦜',
    price: 100,
    description: 'Hồi sinh từ tro tàn, bay cao bất tận.',
  },
  {
    id: 'ninja-star',
    name: 'Phi Tiêu Ninja',
    icon: '🌀',
    price: 70,
    description: 'Đòn đánh nhanh gọn, khó đoán.',
  },
  {
    id: 'space-core',
    name: 'Hạt Nhân Vũ Trụ',
    icon: '🪐',
    price: 120,
    description: 'Sức mạnh xoáy tâm không gian.',
  },
  {
    id: 'slime',
    name: 'Slime Dẻo',
    icon: '🟢',
    price: 60,
    description: 'Lầy lội và khó chịu bất ngờ.',
  },
  {
    id: 'vampire',
    name: 'Ma Cà Rồng',
    icon: '🧛',
    price: 90,
    description: 'Ẩn nấp trong bóng tối, hút máu chiến lược.',
  },
];
